# Generated by Django 5.2.3 on 2025-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=255)),
                ('primary_color', models.CharField(max_length=7)),
                ('secondary_color', models.CharField(max_length=7)),
                ('tertiary_color', models.CharField(blank=True, max_length=7)),
                ('quaternary_color', models.CharField(blank=True, max_length=7)),
            ],
        ),
    ]
