# Generated by Django 5.2.3 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='topic',
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(default='No description yet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='quaternary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='site',
            name='tertiary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
